name: Deploy required aws resources
on: 
  workflow_dispatch: 
env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}       # Example for AWS
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
jobs:
  DeployAWS:
    runs-on: ubuntu-latest 
    steps: 
      # Step 1: Check out the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Pulumi
      - name: Setup Pulumi
        uses: pulumi/actions@v4
        with:
          command: preview    # Change to 'up' for deploying or 'destroy' for teardown

      # Step 3: Install dependencies (if needed for your Pulumi program)
      - name: Install Dependencies
        run: |
          cd /iac 
          pip install -r requirements.txt 

      # Step 4: Run Pulumi command
      - name: Pulumi Update
        run: | 
          cd /iac
          pulumi up --yes
        env:
          PULUMI_CONFIG_PASSPHRASE: ${{ secrets.PULUMI_CONFIG_PASSPHRASE }}  # Optional for encrypted configs      




