name: Common Steps
on:
  workflow_call:
    secrets:
      aws-region:
        required: true
      aws-s3-pulumi:
        required: true
      pulumi-password:
        required: true
      aws-access-key-id:
        required: true      
      aws-secret-access-key:
        required: true
  

jobs:
  common:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.aws-access-key-id }}
          aws-secret-access-key: ${{ secrets.aws-secret-access-key }}
          aws-region: ${{ secrets.aws-region }}

      - name: Login to Pulumi
        run: pulumi login s3://${{ secrets.aws-s3-pulumi }}