name: Common Steps
on:
  workflow_call:
    inputs:
      aws-region:
        required: true
        type: string
      aws-s3-pulumi:
        required: true
        type: string
      pulumi-password:
        required: true
        type: string
      aws-access-key-id:
        required: true
        type: string
      aws-secret-access-key:
        required: true
        type: string

jobs:
  common:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ inputs.aws-access-key-id }}
          aws-secret-access-key: ${{ inputs.aws-secret-access-key }}
          aws-region: ${{ inputs.aws-region }}

      - name: Login to Pulumi
        run: pulumi login s3://${{ inputs.aws-s3-pulumi }}