name: Hprofile Actions 
on: 
  push: 
    branches: 
      - main 
      - dev 
jobs: 
  Testing: 
    runs-on: ubuntu-latest
    steps:
      - name: Code checkout 
        uses: actions/checkout@v4
      
      - name: Maven test 
        run: mvn test
      
      - name: Checkstyle 
        run: mvn checkstyle:checkstyle
      
      - name: Setup Java 11 
        uses: actions/setup-java@v4 
        with: 
          distribution: 'temurin'
          java-version: '11'
      - name: Setup SonarQube
        uses: warchant/setup-sonar-scanner@v7
        # Run sonar-scanner
      - name: SonarQube Scan
        run: sonar-scanner -X
            -Dsonar.host.url=https://sonarcloud.io
            -Dsonar.login=43c6d22c2e59f304c8a7345e47d499f1f655faaa
            -Dsonar.organization=adam-czepiel
            -Dsonar.projectKey=hprofile
            -Dsonar.sources=src/
            -Dsonar.junit.reportsPtah=target/surefire-reports/
            -Dsonar.jacoco.reportsPath=target/jacoco.exec
            -Dsonar.java.checkstyle.reportsPath=target/checkstyle-result.xml
            -Dsonar.java.binaries=target/test-classes/com/visualpathit/account
            -Dsonar.verbose=true
    