name: Hprofile Actions 
on: 
  push: 
    branches: 
      - main 
      - dev 
jobs: 
  Testing: 
    runs-on: ubuntu-latest
    steps:
      - name: Code checkout 
        uses: actions/checkout@v4
      
      - name: Maven test 
        run: mvn test
      
      - name: Checkstyle 
        run: mvn checkstyle:checkstyle
      
      - name: Setup Java 17 
        uses: actions/setup-java@v4 
        with: 
          distribution: 'temurin'
          java-version: '17'
      - name: Setup SonarQube
        uses: warchant/setup-sonar-scanner@v7
        # Run sonar-scanner
      - name: SonarQube Scan
        env: 
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: sonar-scanner -X
            -Dsonar.host.url=${{ secrets.SONAR_URL }}
            -Dsonar.login=${{ secrets.SONAR_TOKEN }}
            -Dsonar.organization=${{ secrets.SONAR_ORAGANIZATION}}
            -Dsonar.projectKey=${{ secrets.SONAR_PROJECT }}
            -Dsonar.sources=src/
            -Dsonar.junit.reportsPath=target/surefire-reports/
            -Dsonar.jacoco.reportsPath=target/jacoco.exec
            -Dsonar.java.checkstyle.reportsPath=target/checkstyle-result.xml
            -Dsonar.java.binaries=target/test-classes/com/visualpathit/account
            -Dsonar.verbose=true
    